### ISSUE TITLE
关于网站的google统计

### ISSUE THREAD

**Issue by liruifengv** [Z4R1TSU/home#1]
hello。看到你使用了我的博客作为模板，很开心你喜欢 Astro。

但是注意到你没有删除 google 统计的代码。

![image](https://github.com/user-attachments/assets/2b49288e-7d9e-40f1-9fad-78e06eea40ea)

在 `BaseLayout.astro` 文件中，有一段代码，是用于访问量统计的。

由于你复制模板之后没有删除，会导致我这里统计错乱。

看到之后删除一下，另外看到一些邮件信息等还是我的~

**Comment by Z4R1TSU** [comment]
首先先表达一下我的歉意。既是回复有点慢了，因为刚好这两天在来学校的路上，今天下午才回到学校比较忙碌；二是抱歉并没有经过您的允许就使用了您的博客模板；三是给您带来了不便，导致您访问量统计的异常。
当我刷到您的博客的时候，我就特别喜欢这个模板样式，所以我花了几天立马把之前简陋的Vue3的基础博客给替换了。因为您的这个项目也是MIT的证，所以也直接clone下来用了。并且我一直都在（从最初发布的一版开始）详情页内，就已经附上了您的Github账号，说明了制作和参考的工具。
在收到您的邮件后，我在第一时间就修改了您在附件图片中指出的这部分代码，并将方框内标出的代码全部删除了。希望之后不会再影响到您。
非常感谢您做出的这个模板，让我发表博客都能心情愉悦，再次感谢您的付出和大度。祝好。

liruifengv ***@***.***> 于2024年8月19日周一 17:51写道：

**Comment by liruifengv** [comment]
没关系，都是开源的随便用。是我偷懒直接把统计代码传上来了，稍后我改成动态注入的。

可以加我微信 liruifengv2333，有一个 Astro 交流群
